spring:
  application:
    name: edunet-backend

  datasource:
    # Am adăugat jdbc: la început și am schimbat portul în 6543
    url: jdbc:postgresql://aws-1-eu-west-2.pooler.supabase.com:6543/postgres?prepareThreshold=0&sslmode=require
    driver-class-name: org.postgresql.Driver
    # Username-ul tău special pentru Pooler
    username: postgres.bnxouxmxpwpspdhwhipk
    password: "ToMo0987.Kiri"
  jpa:
    hibernate:
      # 'update' este cel mai sigur: creează tabelele dacă nu există, dar nu șterge datele vechi
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        # Schimbăm dialectul de la H2 la PostgreSQL
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true



server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.edunet: DEBUG

app:
  jwt:
    secret: 3v7QmG8hK2pX9sL4nD6rT1yU5iO0aS7dF8gH9jK4lZ2xC1vB5nM6qW8eR3tY7uP9sA2dF5gH8jK1
    expiration: 86400000  # 24 hours
